name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Xcode
        uses: actions/setup-xcode@v2
        with:
          xcode-version: '12.x'

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod repo update

      - name: Install dependencies
        run: |
          cd path/to/project
          pod install

      - name: Build app
        run: |
          cd path/to/project
          xcodebuild clean build -workspace YourWorkspace.xcworkspace -scheme YourScheme -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=15.2,name=iPhone 13'
