name: Build iOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build app
        run: |
          cd path/to/project
          xcodebuild clean build -workspace YourWorkspace.xcworkspace -scheme DogsApp -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=15.2,name=iPhone 13'

